name: research_project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312he52fbff_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alphashape=1.3.1=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - aws-c-auth=0.8.6=h660070d_4
  - aws-c-cal=0.8.7=h8f38403_0
  - aws-c-common=0.12.0=h5505292_0
  - aws-c-compression=0.3.1=hd84a0f8_2
  - aws-c-event-stream=0.5.4=h3c33643_2
  - aws-c-http=0.9.4=hedcc1e3_4
  - aws-c-io=0.17.0=ha705ebb_6
  - aws-c-mqtt=0.12.2=h82c6c6a_2
  - aws-c-s3=0.7.13=hb857f95_2
  - aws-c-sdkutils=0.2.3=hd84a0f8_2
  - aws-checksums=0.2.3=hd84a0f8_2
  - aws-crt-cpp=0.31.0=h7378f02_4
  - aws-sdk-cpp=1.11.510=hf067f9e_3
  - azure-core-cpp=1.14.0=hd50102c_0
  - azure-identity-cpp=1.10.0=hc602bab_0
  - azure-storage-blobs-cpp=12.13.0=h7585a09_1
  - azure-storage-common-cpp=12.8.0=h9ca1f76_1
  - azure-storage-files-datalake-cpp=12.12.0=hcdd55da_1
  - blosc=1.21.6=h7dd00d9_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.0.7=hc377ac9_0
  - brotli-python=1.1.0=py312h6b01ec3_4
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - c-blosc2=2.21.2=hb5916c8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py312h0fad829_0
  - charls=2.4.2=h524480c_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click-log=0.4.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h84eede6_3
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h80987f9_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.16=py312he360a15_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - efficientnet-pytorch=0.7.1=pyhd8ed1ab_1
  - eval_type_backport=0.3.0=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h20db955_106
  - flatbuffers=24.12.23=h28594ff_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.0=hce30654_1
  - freexl=2.0.0=h3ab3353_2
  - fribidi=1.0.16=hc919400_0
  - gast=0.6.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7af3d76_3
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.0=h4bcf65f_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312hee6aa52_2
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hec049ff_2
  - grpcio=1.67.1=py312he4e58e5_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py312hd7c5113_100
  - harfbuzz=11.4.5=hf4e55d4_0
  - hdbscan=0.8.39=py312ha11c99a_1
  - hdf5=1.14.3=nompi_ha698983_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imageio=2.37.0=py312hca03da5_0
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=hc0e5025_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jxrlib=1.1=h1a28f6b_2
  - keras=3.11.2=pyh753f3f9_0
  - kiwisolver=1.4.9=py312hd8c8125_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lazy_loader=0.4=py312hca03da5_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libaec=1.1.4=h51d1e36_0
  - libarchive=3.8.1=gpl_h46e8061_100
  - libarrow=19.0.1=h9828ad4_3_cpu
  - libarrow-acero=19.0.1=hf07054f_3_cpu
  - libarrow-dataset=19.0.1=hf07054f_3_cpu
  - libarrow-substrait=19.0.1=h4239455_3_cpu
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libavif16=1.3.0=hf1e31eb_0
  - libblas=3.9.0=35_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=35_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=20.1.8=h8869778_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.0=hce30654_1
  - libfreetype6=2.14.0=h6da58f4_1
  - libgdal-core=3.11.4=h269a1e0_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libglib=2.84.4=h7a3292d_0
  - libgoogle-cloud=2.36.0=hdbe95d5_0
  - libgoogle-cloud-storage=2.36.0=h7081f7f_0
  - libgrpc=1.67.1=h0a426d6_2
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libhwy=1.3.0=hf6a9ce8_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h7274d02_4
  - libkml=1.3.0=hc33e383_1022
  - liblapack=3.9.0=35_hd9741b5_openblas
  - liblapacke=3.9.0=35_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libml_dtypes-headers=0.5.3=h707e725_0
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libopencv=4.11.0=headless_py312hb2e6766_2
  - libopentelemetry-cpp=1.18.0=h0c05b2d_1
  - libopentelemetry-cpp-headers=1.18.0=hce30654_1
  - libopenvino=2025.0.0=h3f17238_2
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_2
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_2
  - libopenvino-auto-plugin=2025.0.0=h7f72211_2
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_2
  - libopenvino-ir-frontend=2025.0.0=h718ad69_2
  - libopenvino-onnx-frontend=2025.0.0=h76e6831_2
  - libopenvino-paddle-frontend=2025.0.0=h76e6831_2
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_2
  - libopenvino-tensorflow-frontend=2025.0.0=he275e1d_2
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_2
  - libopus=1.5.2=h48c0fde_0
  - libparquet=19.0.1=h636d7b7_3_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=5.28.3=h3bd63a1_1
  - libre2-11=2024.07.02=h07bc746_2
  - librsvg=2.58.4=h266df6f_3
  - librttopo=1.1.0=hf7cb3ef_19
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.1.0=h57eeb1c_0
  - libspatialite=5.1.0=h67ea1dc_15
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtensorflow_cc=2.18.0=cpu_hf321e49_1
  - libtensorflow_framework=2.18.0=cpu_h2398287_1
  - libthrift=0.21.0=h64651cc_0
  - libtiff=4.7.0=h025e3ab_6
  - libtorch=2.6.0=cpu_generic_h16e2b10_1
  - libusb=1.0.29=hbc156a2_0
  - libutf8proc=2.10.0=h74a6958_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=hc377ac9_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=20.1.8=hbb9b287_2
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h998013c_1
  - matplotlib-base=3.10.6=py312h605b88b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=hff1a8ea_0
  - ml_dtypes=0.4.0=py312hcd31e36_2
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munch=4.0.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h11e0b38_0
  - namex=0.1.0=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h248ca61_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py312h8442bc7_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencv=4.11.0=headless_py312h06d4b4e_2
  - openexr=3.3.5=haaeed0a_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py312ha0dd364_1
  - orc=2.1.1=h74f7c94_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - pretrainedmodels=0.7.4=pyhd8ed1ab_2
  - proj=9.6.2=hdbeaa80_2
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.28.3=py312hd8f9ff3_0
  - psutil=7.0.0=py312h163523d_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.11.0=headless_py312hd9a6259_2
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.1=py312hb22504d_1
  - pyproj=3.7.2=py312hf0774e8_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=hc22306f_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h692f514_1
  - python_abi=3.12=8_cp312
  - pytorch=2.6.0=cpu_generic_py312_h8a1ee9d_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - re2=2024.07.02=h6589ca4_2
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py312h4409184_1
  - rich=14.1.0=pyhe01879c_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.14.5=h382de68_0
  - safetensors=0.6.2=py312h7a0e18e_2
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - segmentation-models-pytorch=0.5.0=pyh2a12c56_0
  - sentry-sdk=2.44.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py312h4409184_2
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.50.4=hb5dd463_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.2=h8ab69cd_0
  - tbb=2022.3.0=h66ce52b_1
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py312h5fad481_2
  - tensorflow=2.18.0=cpu_py312hb6b62e0_1
  - tensorflow-base=2.18.0=cpu_py312h81ab8d0_1
  - tensorflow-estimator=2.18.0=cpu_py312h5e86b3d_1
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchvision-extra-decoders=0.0.2=py312h2e63e4f_2
  - tornado=6.5.2=py312h163523d_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trimesh=4.10.0=pyh7b2049a_0
  - typer-slim=0.20.0=pyhcf101f3_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py312h4409184_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wandb=0.22.3=py312h7a0e18e_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py312hca03da5_0
  - wrapt=1.17.3=py312h163523d_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xerces-c=3.2.5=h92fc2f4_2
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xxhash=0.8.3=haa4e116_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py312h5748b74_0
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=hfd287c0_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=hf787086_0
  - zstandard=0.24.0=py312h26de6b3_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - affine==2.4.0
      - aiobotocore==2.25.2
      - aioitertools==0.13.0
      - alabaster==1.0.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asciitree==0.3.3
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blinker==1.9.0
      - bokeh==3.5.2
      - botocore==1.40.70
      - cachetools==6.2.0
      - click==8.1.7
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - configparser==7.2.0
      - csbdeep==0.8.1
      - ctk-cli==1.5
      - dask==2024.10.0
      - dask-expr==1.1.16
      - datasets==4.4.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dicomweb-client==0.59.3
      - dill==0.4.0
      - diskcache==5.6.3
      - distributed==2024.10.0
      - docutils==0.21.2
      - dynaconf==3.2.11
      - eval-type-backport==0.2.2
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - flask==3.1.0
      - flask-cors==5.0.0
      - fonttools==4.59.2
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - funcsigs==1.0.2
      - gdown==5.2.0
      - girder-client==3.2.11
      - girder-slicer-cli-web==1.5.14
      - glymur==0.13.6
      - hf-xet==1.1.10
      - histomicstk==1.4.0
      - huggingface-hub==0.35.3
      - imagecodecs==2024.9.22
      - imagecodecs-numcodecs==2025.3.30
      - imagesize==1.4.1
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jmespath==1.0.1
      - jpype1==1.6.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - large-image==1.33.0
      - large-image-source-deepzoom==1.33.0
      - large-image-source-dicom==1.33.0
      - large-image-source-multi==1.33.0
      - large-image-source-nd2==1.33.0
      - large-image-source-openslide==1.33.0
      - large-image-source-pil==1.33.0
      - large-image-source-rasterio==1.33.0
      - large-image-source-test==1.33.0
      - large-image-source-tifffile==1.33.0
      - large-image-source-zarr==1.33.0
      - lark==1.3.0
      - llvmlite==0.45.1
      - locket==1.0.0
      - lxml==6.0.2
      - mako==1.3.10
      - marshmallow==3.26.1
      - matplotlib==3.9.3
      - mistune==3.1.4
      - morecantile==6.2.0
      - msgpack==1.1.1
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nd2==0.10.3
      - nimfa==1.4.0
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numcodecs==0.15.1
      - ome-types==0.6.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.11.0.86
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.1
      - palettable==3.3.3
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - paquo==0.9.0
      - partd==1.4.2
      - pillow==11.0.0
      - pillow-heif==1.1.1
      - pillow-jxl-plugin==1.3.4
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydicom==3.0.1
      - pynndescent==0.5.13
      - pyopencl==2025.2.6
      - pyparsing==3.2.3
      - python-json-logger==4.0.0
      - pytools==2025.2.4
      - pyvips==3.0.0
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - rawpy==0.25.1
      - referencing==0.36.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - resource-backed-dask-array==0.1.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rio-cogeo==5.4.2
      - rpds-py==0.27.1
      - s3fs==2025.10.0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==80.9.0
      - shapely==2.0.6
      - simpleitk==2.4.0
      - simplejpeg==1.8.2
      - simsimd==6.5.3
      - siphash24==1.8
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - spams-bin==2.6.12
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.43
      - stardist==0.9.1
      - stringzilla==4.2.1
      - sympy==1.13.1
      - tblib==3.1.0
      - terminado==0.18.1
      - tiatoolbox==1.6.0
      - tifffile==2024.9.20
      - tiffile==2018.10.18
      - tifftools==1.6.1
      - timm==1.0.12
      - tinycss2==1.4.0
      - tokenizers==0.15.2
      - tol-colors==2.1.0
      - toolz==1.0.0
      - torch==2.5.1
      - torchvision==0.20.1
      - transformers==4.36.0
      - umap==0.1.1
      - umap-learn==0.5.9.post2
      - universal-pathlib==0.2.6
      - uri-template==1.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - wsidicom==0.22.0
      - xsdata==24.3.1
      - xyzservices==2025.4.0
      - zarr==2.18.3
      - zict==3.0.0
