name: ason
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - tk
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - jupyter
  - jupyterlab
  - networkx
  - tifffile
  - hydra-core
  - omegaconf
  - segmentation-models-pytorch
  - tensorflow
  - tensorboard
  - wandb
  - pip:
      - stardist
      - albumentations
      - tiatoolbox
      - pyyaml
      - tqdm
      - geopandas
      - shapely
      - alphashape
      - opencv-python-headless
      - zarr<3.0.0
      - numcodecs<0.14.0
      - python-dotenv
      - torchmetrics
      - torch
      - torchvision
