name: ason
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - jupyter
  - jupyterlab
  - networkx
  - tifffile
  - pytorch
  - torchvision
  - segmentation-models-pytorch
  - tensorboard
  - wandb
  - pip:
      - stardist
      - albumentations
      - tiatoolbox
      - pyyaml
      - tqdm
      - geopandas
      - shapely
      - alphashape
      - opencv-python-headless
